from sympy import*
x,y,z,r,theta,i,j,k,e_r,e_theta,e_z = symbols("x,y,z,r,theta,i,j,k,e_r,e_theta,e_z")
m = r*cos(theta)
n = r*sin(theta)
p = (cos(theta)*e_r)-(sin(theta)*e_theta)
q = (sin(theta)*e_r)-(cos(theta)*e_theta)
f = (x*i +y*j +z*k)
w = simplify(f.subs([(x,m),(y,n),(z,z),(i,p),(j,q),(k,s)]))
print("The Cylidrical coordinate is ",w )
f1 = w.coeff(e_r)
f2 = w.coeff(e_theta)
f3 = w.coeff(e_z)
a = (1/r)*diff(r*f1,r)
b = (1/r)*diff(f2,theta)
c = diff(f3)
print("The Divergence is ",a+b+c)
a1 = ((1/r)*diff(f3,theta))-diff(f2,z)
b1 = diff(f1,z)-diff(f3,r)
c1 = (1/r)*diff(r*f2,r)-diff(f1,theta)
print("The Curl is (",a1,")e_r + (",b1,")e_theta + (",c1,")e_z")
